name : Alan Höng - kayibal
brand : Alan Höng
description : yound, driven computer scientist with academic background
keyword : 
url : http://kayibal.github.io
email : alan.f.hoeng@gmail.com
github : kayibal
author : Alan Höng
analytics : UA-8418273-8
year : 2016
markdown : kramdown
exclude :
  - node_modules
